# Config file for automatic testing at travis-ci.org

language: python
dist: xenial
python:
  - 3.7

stages:
  - test
  - name: answers
    if: branch = master

jobs:
  include:
    - stage: test
      install:
        - pip install pipenv
        - pipenv install --dev --ignore-pipfile --deploy --system
      before_script: # code coverage tool
         - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
         - chmod +x ./cc-test-reporter
         - ./cc-test-reporter before-build
      script: pytest --cov-report xml --cov-report term
      after_script:
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
    - stage: answers
      script: python3 fibonacci.py
      name: "Fibonacci"
    - script: python3 pyramid.py
      name: "Pyramid"